version: "3.7"
services:
  sb-app:
    build: .
    container_name: "springboot-mongo"
    ports:
      - '8081:8081'
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017